name: voila
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipywidgets
  - ipykernel
  - pandas
  - pip
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - jupyterlab-fasta=3.3.0
  - matplotlib
  - scipy
  - vega_datasets
  - ipyvolume
  - tabulate

  - pip:
    - voila==0.5.8
    - voila-topbar==0.1.1
