name: voila
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipywidgets
  - ipykernel
  - pandas
  - pip
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - jupyterlab-fasta>= 4.0.0
  - matplotlib
  - scipy
  - vega_datasets
  - ipyvolume

  - pip:
    - voila==0.5.8
    - voila-topbar==0.1.1
